/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-27 06:50:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <footer id=\"footer\" class=\"bg-dark text-light py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-6 col-md-6 col-lg-3 mb-2\">\r\n");
      out.write("                    <h6 class=\"text-uppercase\">Tools</h6>\r\n");
      out.write("                    <ul class=\"nav flex-column\">\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"ext\" rel=\"nofollow\" href=\"https://themestr.app\" title=\"Bootstrap theme builder\">Themestr.app</a></li>\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"ext\" rel=\"nofollow\" href=\"http://themes.guide\" title=\"Bootstrap free and pro themes\">Themes.guide</a></li>\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"ext\" rel=\"nofollow\" href=\"http://codeply.com\" title=\"Prototype and edit code for Bootstrap and other responsive frameworks\">Codeply</a></li>\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"ext\" rel=\"nofollow\" href=\"http://bootply.com\">Bootply</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-6 col-md-6 col-lg-3 mb-2\">\r\n");
      out.write("                    <h6 class=\"text-uppercase\">More</h6>\r\n");
      out.write("                    <ul class=\"nav flex-column\">\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"_new\" href=\"http://wdstack.com\" title=\"The top projects, tools and apps for Web developers\">WDStack</a></li>\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"_new\" href=\"http://theme.cards\">Theme.cards</a></li>\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"_new\" href=\"http://www.bootbundle.com\">BootBundle</a></li>\r\n");
      out.write("                        <li><a class=\"text-white\" target=\"_new\" title=\"Learn about Bootstrap 4 using this free theme\" href=\"http://bootstrap4.guide\">Bootstrap4.guide</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-md-12 col-lg-6 mb-2 text-right\">\r\n");
      out.write("                    <h6 class=\"text-uppercase\">Follow</h6>\r\n");
      out.write("                    <ul class=\"nav float-right\">\r\n");
      out.write("                        <li><a class=\"text-white mr-2\" rel=\"nofollow\" href=\"http://twitter.com/ThemesGuide\" title=\"Follow on Twitter\"><i class=\"h1 fa fa-fw fa-twitter fa-2x ion-logo-twitter\"></i></a></li>\r\n");
      out.write("                        <li><a class=\"text-white mr-2\" rel=\"nofollow\" href=\"https://www.facebook.com/codeply\" title=\"Follow on Facebook\"><i class=\"h1 fa fa-fw fa-facebook fa-2x ion-logo-facebook\"></i></a></li>\r\n");
      out.write("                        <li><a class=\"text-white mr\" rel=\"nofollow\" href=\"https://github.com/ThemesGuide/bootstrap-themes\" title=\"Follow on GitHub\"><i class=\"h1 fa fa-fw fa-facebook fa-2x ion-logo-github\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/row-->\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
