/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-27 06:50:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Fresca Bootstrap 4 Theme Full Screen</title>\r\n");
      out.write("    <Style>\r\n");
      out.write("    </Style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\"#navbar1\" data-offset=\"60\">\r\n");
      out.write("    <header class=\"bg-primary\">\r\n");
      out.write("        <div class=\"container h-100\">\r\n");
      out.write("            <div class=\"row h-100\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"text-center m-0 vh-100 d-flex flex-column justify-content-center text-light\">\r\n");
      out.write("                        <h1 class=\"display-4\">PetCozi</h1>\r\n");
      out.write("                        <p class=\"lead\">Like a sunny summer day in Northern Italy.</p>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-4 col-sm-6 mx-auto\">\r\n");
      out.write("                                <div class=\"input-group mb-3\">\r\n");
      out.write("                                  <input type=\"text\" class=\"form-control form-control-lg\" placeholder=\"your@email\">\r\n");
      out.write("                                  <div class=\"input-group-append\">\r\n");
      out.write("                                    <button class=\"btn btn-outline-light btn-lg rounded-right\" type=\"button\">Sign-up</button>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt-2 mx-auto\">\r\n");
      out.write("                                                            <div class=\"btn-group\">\r\n");
      out.write("                                  <a href=\"theme.css\" class=\"btn btn-outline-light btn-lg\">\r\n");
      out.write("                                    Download Theme\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <button type=\"button\" class=\"btn btn-lg btn-outline-light dropdown-toggle dropdown-toggle-split\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                    <span class=\"sr-only\">Downloads</span>\r\n");
      out.write("                                  </button>\r\n");
      out.write("                                  <div class=\"dropdown-menu\">\r\n");
      out.write("                                      <a class=\"dropdown-item\" href=\"theme.css\">theme.css</a>\r\n");
      out.write("                                      <a class=\"dropdown-item\" href=\"theme.min.css\">theme.min.css</a>\r\n");
      out.write("                                      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                      <a class=\"dropdown-item\" href=\"theme.scss\">theme.scss</a>\r\n");
      out.write("                                      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                      <a class=\"dropdown-item\" target=\"new\" href=\"https://github.com/ThemesGuide/bootstrap-themes/tree/master/fresca\">Full template</a>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div> \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/nav.jsp", out, false);
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"container\">\r\n");
      out.write("            <div class=\"row vh-100\">\r\n");
      out.write("                <div class=\"col-12 my-auto\">\r\n");
      out.write("                    <div class=\"row text-center\">\r\n");
      out.write("                        <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                            <div class=\"card h-100\">\r\n");
      out.write("                                <div class=\"card-body d-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                    <h1 class=\"display-2 text-primary\"><span class=\"ion ion-ios-snow-outline\"></span></h1>\r\n");
      out.write("                                    <h4 class=\"card-title text-primary\">Unique</h4>\r\n");
      out.write("                                    <p class=\"card-text\">Don't like that typical Bootstrap look? Each theme has a custom look-and-feel, while maximizing use of Bootstrap without extensive additional CSS & JS.</p>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-primary mt-auto\">Button</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                            <div class=\"card h-100\">\r\n");
      out.write("                                <div class=\"card-body d-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                    <h1 class=\"display-2 text-primary\"><span class=\"ion ion-ios-tablet-portrait-outline\"></span></h1>\r\n");
      out.write("                                    <h4 class=\"card-title text-primary\">Responsive</h4>\r\n");
      out.write("                                    <p class=\"card-text\">Based on mobile-first Bootstrap 4, all themes are 100% responsive and designed to look great on everything from smartphones to tablets to desktops..</p>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-primary mt-auto\">Button</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                            <div class=\"card h-100\">\r\n");
      out.write("                                <div class=\"card-body d-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                    <h1 class=\"display-2 text-primary\"><span class=\"ion ion-ios-checkmark-circle-outline\"></span></h1>\r\n");
      out.write("                                    <h4 class=\"card-title text-primary\">Consistent</h4>\r\n");
      out.write("                                    <p class=\"card-text\">Themes are crafted with care for design and performance. All themes are built on modern HTML5 & CSS3 standards to ensure consistency and cross-browser support.</p>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-primary mt-auto\">Button</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("                <section id=\"buttons\" class=\"pb-5\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-9\">\r\n");
      out.write("                        <div class=\"pb-3\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary mr-1\">Primary #07689F</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-outline-primary\">Outline</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pb-3\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary align-bottom btn-lg mr-1\">Large</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary align-bottom mr-1\">Normal</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary align-bottom btn-sm mr-1\">Small</button>\r\n");
      out.write("                            <a href=\"#\" class=\"text-primary\">Text</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md d-none d-sm-block\">\r\n");
      out.write("                        <h4>Code Explorer</h4>\r\n");
      out.write("                        <p>\r\n");
      out.write("                        Just hover over any of the Bootstrap \r\n");
      out.write("                        components, and click the \r\n");
      out.write("                        <span class=\"d-inline-block rounded border align-middle pb-1 px-1 small\"><small>&lt;&gt;</small></span>\r\n");
      out.write("                        to view or copy the HTML markup for that element.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row py-2\">\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-secondary\">Secondary</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-info\">Info</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-danger\">Danger</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-success\">Success</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-warning\">Warning</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-light\">Light</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-outline-dark\">Dark</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row py-2\">\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-secondary\">Secondary</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-info\">Info</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-danger\">Danger</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-success\">Success</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-warning\">Warning</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-light\">Light</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-auto col-3\">\r\n");
      out.write("                        <button class=\"btn btn-dark\">Dark</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"navs\" class=\"container pb-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-9 pb-4\">\r\n");
      out.write("                    <nav class=\"navbar navbar-expand-md navbar-dark bg-primary mb-2\">\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"#\">Light text</a>\r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarColor02\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarColor02\">\r\n");
      out.write("                            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"#\" title=\"Current breakpoint tier\">\r\n");
      out.write("                                        Tier     \r\n");
      out.write("                                        <span class=\"d-xl-inline d-none\">XL</span>\r\n");
      out.write("                                        <span class=\"d-lg-inline d-xl-none d-none\">LG</span>\r\n");
      out.write("                                        <span class=\"d-md-inline d-lg-none d-none\">MD</span>\r\n");
      out.write("                                        <span class=\"d-sm-inline d-md-none d-none\">SM</span>\r\n");
      out.write("                                        <span class=\"d-inline d-sm-none\">XS</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"#\">About</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <nav class=\"navbar navbar-expand-md navbar-light bg-primary mb-3\">\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"#\">Dark text</a>\r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarColor03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarColor03\">\r\n");
      out.write("                            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"#\">About</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <div class=\"card border-0\">\r\n");
      out.write("                        <ul class=\"nav nav-tabs\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link active\" href=\"#tab1\" data-toggle=\"tab\">Tab</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#tab2\" data-toggle=\"tab\">Tab</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#tab3\" data-toggle=\"tab\">Tab</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link disabled\" href=\"#tab4\" data-toggle=\"tab\">Disabled</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"tab-content px-1 pt-3\">\r\n");
      out.write("                            <div class=\"tab-pane active\" id=\"tab1\">\r\n");
      out.write("                                Select a palette, change the <span class=\"text-primary \">primary</span>, <span class=\"text-secondary \">secondary</span>, \r\n");
      out.write("                                <span class=\"text-success \">success</span>, <span class=\"text-danger \">danger</span>, \r\n");
      out.write("                                <span class=\"text-info \">info</span>, and <span class=\"text-warning \">warning</span> colors. \r\n");
      out.write("                                Choose from various Google Fonts, and modify most of the Bootstrap SASS variables. Click to generate your completely custom \r\n");
      out.write("                                Bootstrap theme.\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"tab2\">\r\n");
      out.write("                                The whole idea is to make the Bootstrap customization process easier, and allow you to visualize changes along the way. \r\n");
      out.write("                                For most users it's designed to be point-and-click, while advanced users can delve into the SASS as desired. It's a 4-step process.\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"tab3\">3. Put some more content in your pane here.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-3 pb-4\">\r\n");
      out.write("                    <ul class=\"nav nav-pills flex-column mb-3\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link active\" href=\"#\">Active</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"btn-group mb-3 w-100\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary btn-block\">Dropdown</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary dropdown-toggle dropdown-toggle-split\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            <span class=\"sr-only\">Toggle Dropdown</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"#\">Link</a>\r\n");
      out.write("                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"#\">Separated link</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"cards\" class=\"container pb-5\">\r\n");
      out.write("            <div class=\"d-flex my-3\">\r\n");
      out.write("                <div class=\"jumbotron w-100 py-5 mx-auto\">\r\n");
      out.write("                    <h1>Themestr.app</h1>\r\n");
      out.write("                    <h4>Theme Builder for Bootstrap</h4>\r\n");
      out.write("                    <p class=\"lead\">\r\n");
      out.write("                        Rapidy build custom themes for Bootstrap, the world's most \r\n");
      out.write("                        popular front-end component library for mobile-first, \r\n");
      out.write("                        responsive Web apps. <a class=\"font-weight-bold\" href=\"https://themestr.app\">Themestr.app</a> is a customizer and theme creator for Bootstrap. \r\n");
      out.write("                        Choose from a huge collection of color palettes, fonts and SASS variables. Prototype different styles, and \r\n");
      out.write("                        easily generate CSS from SASS to give your projects a unique look-and-feel.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"card border-primary h-100\">\r\n");
      out.write("                        <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                            <h4 class=\"card-title text-primary\">Card Outline</h4>\r\n");
      out.write("                            <p class=\"card-text\">Themestr.app makes it easy to customize this, and other free Bootstrap 4 themes for your downloading pleasure.</p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary mt-auto\">Button</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"card border-primary h-100\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"list-group\">\r\n");
      out.write("                                <a href=\"#\" class=\"list-group-item list-group-item-action active\">Dis List Group</a>\r\n");
      out.write("                                <a href=\"#\" class=\"list-group-item list-group-item-action\">Custom Colors</a>\r\n");
      out.write("                                <a href=\"#\" class=\"list-group-item list-group-item-action\">Google Fonts</a>\r\n");
      out.write("                                <a href=\"#\" class=\"list-group-item list-group-item-action disabled\">Ionicons</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"card bg-primary text-white h-100\">\r\n");
      out.write("                        <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                            <h4 class=\"card-title\">Scrollspy</h4>\r\n");
      out.write("                            <p class=\"card-text\">The top NavBar utilizes Bootstrap's Scrollspy component. You'll notice when you scroll the page the \"active\" nav section is highlighted.</p>\r\n");
      out.write("                            <a href=\"https://getbootstrap.com/docs/4.1/components/scrollspy/\" class=\"btn btn-primary border-white mt-auto\">Read More</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"modals\" class=\"container pb-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"container-fluid\">\r\n");
      out.write("                        <div class=\"position-relative\" style=\"z-index:1000\">\r\n");
      out.write("                            <div id=\"myModal\" class=\"modal d-block position-relative\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("                            <div class=\"modal-dialog\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <div class=\"modal-header\">\r\n");
      out.write("                                        <h3>Modal</h3>\r\n");
      out.write("                                        <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-body\">\r\n");
      out.write("                                        <p>This is a basic Bootstrap 4 modal. The modal also comes in a <a href=\"#modal-sm\" data-toggle=\"modal\">smaller</a> and <a href=\"#modal-lg\" data-toggle=\"modal\">larger</a> sizes.</p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            What will you put in your modal? Lorem ipsum dolor sit amet, consectetur adipiscing elit. \r\n");
      out.write("                                            in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan. Aliquam in felis sit amet augue.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-footer\">\r\n");
      out.write("                                        <button class=\"btn\" data-dismiss=\"alert\" aria-hidden=\"true\">Close</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-9\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"typography\" class=\"container pb-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <h4><a target=\"_new\" href=\"https://fonts.google.com/specimen/Muli\">Muli</a></h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-4\">\r\n");
      out.write("                    <h6>Heading 6</h6>\r\n");
      out.write("                    <h5>Heading 5</h5>\r\n");
      out.write("                    <h4>Heading 4</h4>\r\n");
      out.write("                    <h3 class=\"text-truncate\">Heading 3</h3>\r\n");
      out.write("                    <h2 class=\"text-truncate\">Heading 2</h2>\r\n");
      out.write("                    <h1 class=\"text-truncate\">Heading 1</h1>\r\n");
      out.write("                    <p class=\"lead\">Lead</p>\r\n");
      out.write("                    <p>Paragraph</p>\r\n");
      out.write("                    <span class=\"badge badge-dark\">badge</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-8 text-right\">\r\n");
      out.write("                    <p class=\"display-4 text-truncate\">Display 4</p>\r\n");
      out.write("                    <p class=\"display-3 text-truncate\">Display 3</p>\r\n");
      out.write("                    <p class=\"display-2 text-truncate\">Display 2</p>\r\n");
      out.write("                    <p class=\"display-1 text-truncate\">Display 1</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"forms\" class=\"container pb-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <form role=\"form\">\r\n");
      out.write("                        <div class=\"form-group row\">\r\n");
      out.write("                            <label class=\"col-md-2 col-form-label form-control-label text-muted\">First</label>\r\n");
      out.write("                            <div class=\"col-md-4\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" value=\"Jane\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <label class=\"col-md-1 col-form-label form-control-label text-muted\">Last</label>\r\n");
      out.write("                            <div class=\"col-md-5\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" value=\"Bishop\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group row\">\r\n");
      out.write("                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\">Address</label>\r\n");
      out.write("                            <div class=\"col-lg-10\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" placeholder=\"Street\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group row\">\r\n");
      out.write("                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\"></label>\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" placeholder=\"City\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4\">\r\n");
      out.write("                                <select class=\"form-control\">\r\n");
      out.write("                                    <option>State</option>\r\n");
      out.write("                                    <option>AK</option>\r\n");
      out.write("                                    <option>AZ</option>\r\n");
      out.write("                                    <option>CA</option>\r\n");
      out.write("                                    <option>CO</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group row was-validated\">\r\n");
      out.write("                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\">Username</label>\r\n");
      out.write("                            <div class=\"col-lg-10\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" required=\"\" id=\"un\" name=\"un\">\r\n");
      out.write("                                <div class=\"invalid-feedback\">\r\n");
      out.write("                                  Username is required.\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group row\">\r\n");
      out.write("                            <label class=\"col-lg-2 col-form-label form-control-label\"></label>\r\n");
      out.write("                            <div class=\"col-lg-10\">\r\n");
      out.write("                                <input type=\"reset\" class=\"btn btn-outline-secondary mr-2\" value=\"Cancel\">\r\n");
      out.write("                                <input type=\"button\" class=\"btn btn-primary mr-2\" value=\"Submit\">\r\n");
      out.write("                                <div class=\"custom-control custom-checkbox d-inline\">\r\n");
      out.write("                                  <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck\" checked>\r\n");
      out.write("                                  <label class=\"custom-control-label\" for=\"customCheck\">Check me out</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"grid\" class=\"container pb-5\">\r\n");
      out.write("            <p class=\"lead\">The rows &amp; columns of the world famous Bootstrap grid speak for themselves.</p>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    6\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-6\">\r\n");
      out.write("                    <div class=\"card my-1 bg-light\">6</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-5\">\r\n");
      out.write("                    5\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-7\">\r\n");
      out.write("                    <div class=\"card my-1\">7</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-4\">\r\n");
      out.write("                    4\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                    <div class=\"card my-1\">8</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-3\">\r\n");
      out.write("                    3\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-9\">\r\n");
      out.write("                    <div class=\"card my-1\">9</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-2\">\r\n");
      out.write("                    2\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                    <div class=\"card my-1\">10</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-1\">\r\n");
      out.write("                    1\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-11\">\r\n");
      out.write("                    <div class=\"card my-1\">11</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"more\" class=\"container pb-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table table-hover table-sm\">\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th class=\"w-25\">Location</th>\r\n");
      out.write("                                    <th class=\"w-50\">Date</th>\r\n");
      out.write("                                    <th class=\"w-25\">Visits</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>Westfield</td>\r\n");
      out.write("                                    <td>08.05.18 <span class=\"badge badge-primary\">badge</span></td>\r\n");
      out.write("                                    <td>2323</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>Galway</td>\r\n");
      out.write("                                    <td>08.05.18 <span class=\"badge badge-pill badge-primary\">badge-pill</span></td>\r\n");
      out.write("                                    <td>5362</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"table-primary\">\r\n");
      out.write("                                    <td>Bern</td>\r\n");
      out.write("                                    <td>08.05.18</td>\r\n");
      out.write("                                    <td>153</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"w-100 my-4\"></div>\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-primary\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"This tooltip is on the right.\">Right tooltip (hover)</a>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <a href=\"#\" class=\"text-primary\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"This tooltip is on the bottom.\">Bottom tooltip (hover)</a>\r\n");
      out.write("                    <br>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 text-right\">\r\n");
      out.write("                    <!--\r\n");
      out.write("                    <div class=\"px-4 p-2 rounded bg-primary text-light\" data-toggle=\"popover\" title=\"Popover title\" data-content=\"And here's some amazing content. It's very engaging. Right?\">\r\n");
      out.write("                        Toggle my popover\r\n");
      out.write("                    </div>-->\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-lg btn-primary\" data-toggle=\"popover\" title=\"Popover title\" data-content=\"And here's some amazing content. It's very engaging. Right?\">Toggle my popover</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"w-100 my-4\"></div>\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"progress mb-2\">\r\n");
      out.write("                        <div class=\"progress-bar bg-primary w-25\" role=\"progressbar\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"alert alert-primary alert-dismissable show fade\" role=\"alert\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
      out.write("                            <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <strong>Well done!</strong> You successfully read this important alert message.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"w-100 my-4\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    <script src=\"//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
